name: CutTag
channels:
  - defaults
  - conda-forge
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://anaconda.org
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_16
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bc=1.07.1=h7f98852_0
  - bedtools=2.31.1=h13024bc_3
  - binutils_impl_linux-64=2.45=h9d8b0ac_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h1ea3ea9_openblas
  - bowtie2=2.5.4=he96a11b_6
  - brotlicffi=1.1.0.0=py311h1ddb823_3
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - contourpy=1.3.3=py311hdf67eae_3
  - curl=8.17.0=h4e3cde8_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.16.2=h5bd4931_0
  - deeptools=3.5.6=pyhdfd78af_0
  - deeptoolsintervals=0.1.9=py311hd891ce7_11
  - docutils=0.21.2=py311h06a4308_1
  - expat=2.7.1=hecca717_0
  - fastp=1.0.1=heae3180_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.60.1=py311hee96239_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=h36674fd_7
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gfortran_impl_linux-64=15.2.0=h9a99ed0_7
  - giflib=5.2.2=hd590300_0
  - glib=2.86.1=hbcf1ec1_2
  - glib-tools=2.86.1=hf516916_2
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=h6e002af_7
  - harfbuzz=12.2.0=h15599e2_0
  - homer=5.1=pl5262h9948957_0
  - htslib=1.22.1=h566b1c6_0
  - icu=75.1=he02047a_0
  - idna=3.11=py311h06a4308_0
  - imagesize=1.4.1=py311h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - isa-l=2.31.1=hb9d3cd8_1
  - jansson=2.14.1=hb9d3cd8_0
  - jinja2=3.1.6=py311h06a4308_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=15.2.0=hcb64138_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.86.1=h32235b2_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=h46f56fc_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=15.2.0=h56912e6_7
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=15.2.0=hcb64138_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h9d88235_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - make=4.4.1=hb9d3cd8_2
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - narwhals=2.11.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nomkl=3.0=0
  - numpy=2.3.4=py311h816806e_1
  - numpy-base=2.3.4=py311h7203c5b_1
  - numpydoc=1.9.0=pyhe01879c_1
  - openblas=0.3.30=h5426c36_2
  - openblas-devel=0.3.30=h557178c_2
  - openjdk=25.0.1=h5755bd7_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=py311h06a4308_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - perl=5.40.2=0_h5eee18b_perl5
  - picard=3.4.0=hdfd78af_0
  - pillow=12.0.0=py311h07c5bb8_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plotly=6.4.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py2bit=0.3.3=py311haab0aaa_1
  - pybigwig=0.3.24=py311hd8c7dd8_0
  - pycparser=2.23=py311h06a4308_0
  - pygments=2.19.2=py311h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysam=0.23.3=py311hb456a96_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hd63d673_2_cpython
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - r-base=4.5.2=hc038350_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_1
  - roman-numerals-py=3.1.0=py311h06a4308_0
  - samtools=1.22.1=h96c455f_0
  - scipy=1.16.3=py311he2bc341_0
  - sed=4.9=hb25bd0a_0
  - seqkit=2.10.1=he881be0_0
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snowballstemmer=3.0.1=py311h06a4308_0
  - sphinx=8.2.3=py311h5eee18b_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.15=h54e0aa7_0
  - tktable=2.10=h8d826fa_7
  - tomli=2.3.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unzip=6.0=hb03c661_4
  - urllib3=2.5.0=py311h06a4308_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxt=1.3.1=h9b100fa_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cython==0.29.37
      - macs2==2.2.9.1
prefix: /home/natsume/tools/miniconda3/envs/CutTag
